In [2]:
import pandas as pd
from datetime import datetime
import tqdm

In [5]:
df = pd.read_csv('features_codes_38_Dec.csv')
df.head()

,id,101,106,201,202,204,207,209,211,218,...,231,232,235,237,238,239,240,242,243,999
0,21-186G-1161,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,21-186G-1172,44.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,21-186G-1190,19.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,21-186G-1193,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,21-186G-12,37.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
olya_simple_features_Dec = pd.read_csv('olya_simple_features_Dec.csv')
olya_simple_features_Dec.head()

             id  q     v_l     sum_b  percent  target
0  21-186G-1161  0   20.23    726.52     0.06     1.0
1  21-186G-1172  1  434.45  15682.25   229.48     1.0
2  21-186G-1190  2  199.07   7246.41   472.80     1.0
3  21-186G-1193  1   72.31   2747.25     0.00     1.0
4    21-186G-12  2  842.01  31279.70   910.83     0.0

In [ ]:
ksusha_features =  pd.read_csv()

In [7]:
X = df.set_index('id').join(olya_simple_features_Dec.set_index('id')).join(ksusha_features.set_index('id'))
X.head()

,101,106,201,202,204,207,209,211,218,220,...,239,240,242,243,999,q,v_l,sum_b,percent,target
id,,,,,,,,,,,,,,,,,,,,,
21-186G-1161,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,20.23,726.52,0.06,1.0
21-186G-1172,44.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1,434.45,15682.25,229.48,1.0
21-186G-1190,19.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2,199.07,7246.41,472.80,1.0
21-186G-1193,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1,72.31,2747.25,0.00,1.0
21-186G-12,37.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2,842.01,31279.70,910.83,0.0

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [ ]:
clf = RandomForestClassifier(max_depth=4, random_state=0)
clf.fit(X.drop('target'), X['target'])

In [ ]:
cross_val_score(clf, X.iloc[:,:-1], X.iloc[:,-1], scoring='roc_auc', cv = 3).mean()

In [ ]:
from sklearn import linear_model
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()
scaler.fit(X.drop('target', axis=1))
scaler.transform(X.drop('target', axis=1))

In [ ]:
logreg = linear_model.LogisticRegression(C=1e5, n_jobs=10)

In [ ]:
cross_val_score(logreg, X.drop('target', axis=1), X['target'], scoring='roc_auc', cv = 3).mean()